#+title: Stig's Soap Box

This is my personal website. There are many like it, but this one is
mine. Sometimes I blog because I have something to say, sometimes it's
just to practice writing. It used to be that most articles were tech
related, but I think that ship has sailed now.

The [[file:articles.org][articles]] page has a full list of articles, in reverse
chronological order of publishing. I also maintain a separate [[file:theindex.org][concept
index]]. Below is a selection of articles that are either my own
favourites, or are particularly popular with readers.

* [[file:articles/2017/n-queens.org][N Queens in Clojure]]

Solving the problem of putting N Queens on an /N/ by /N/ chess board
without them being able to threaten eachother.

* [[file:articles/2016/fizzbuzz.org][FizzBuzz]]

Breakdown of my Tweetable FizzBuzz created using sed and xargs.

* [[file:articles/2016/overcoming-rsi.org][Overcoming RSI]]

Early 2005 I encountered a bad bout of RSI. Prompted by a comment on
the Lobsters forum, I thought I'd share my experience.

* [[file:articles/2016/modsec-and-puppet.org][ModSecurity and Puppet Spelunking]]

In which I investigate how to configure =SecAuditLogParts= for
ModSecurity with Puppet, and find I have to contribute a patch to make
it possible.

** [[file:articles/2014/spray-example.org][Spray Example]]
** [[file:articles/2013/spray-routing-error-handling.org][Spray Routing Error Handling]]
** [[file:articles/2013/scala-slick-postgresql-unit-tests.org][Scala, Slick & PostgreSQL Unit Tests]]
** [[file:articles/2013/scalatest-with-akka.org][Using ScalaTest with Akka]]
** [[file:articles/2013/injecting-akka-testprobe.org][Injecting Akka's TestProbe in place of child actors]]
** [[file:articles/2008/resizable-grid-of-calayers.org][Creating a resizable grid of CALayers]]
** [[file:articles/2007/game-tree-search.org][MiniMax and AlphaBeta Search]]
** [[file:articles/2006/generating-bar-charts-with-sql.org][Generating Bar Charts with SQL]]
** [[file:articles/2006/a-lesson-in-testing.org][A lesson in testing]]
** [[file:articles/2006/rise-of-the-machine.org][Rise of the Machine]]
** [[file:articles/2006/regular-expressions.org][Regular Expressions]]
