version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  emacs26:
    working_directory: ~/blog
    docker:
      - image: silex/emacs:master
  python3:
    docker:
      - image: circleci/python:3.7

jobs:
  build:
    executor: emacs26
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-org-{{ .Branch }}
            - v5-org-trunk
      - run:
          name: Tangle CSS
          command: >
            emacs --batch
            --eval "(require 'ob-tangle)"
            --eval '(org-babel-tangle-file "style.org")'
# TODO: Tangle to a different file above, and insert a "dropcss" step here to remove unnused styles
      - run:
          name: Publish Blog
          command: >
            emacs --batch
            --load .circleci/deps.el
            --load .circleci/config.el
            --funcall org-publish-all
      - store_artifacts:
          path: ~/blog
          destination: html
      - save_cache:
          key: v5-org-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.emacs.d
      - persist_to_workspace:
          root: ~/blog
          paths:
            - '*'

  deploy:
    executor: python3
    steps:
      - attach_workspace:
          at: ~/blog
      - aws-s3/sync:
          from: ~/blog
          to: 's3://www.brautaset.org'
          arguments: >-
            --delete
            --exclude '*'
            --include '*.png'
            --include '*.pdf'
            --include '*.jpg'
            --include '*.html'
            --include '*.xml'
            --acl public-read
            --cache-control "max-age=86400"
      - run: >-
          aws cloudfront create-invalidation
          --distribution-id E2HQ2C8QF1FXUZ
          --paths '/*'

workflows:
  version: 2

  pr:
    jobs:
      - build:
          filters:
            branches:
              ignore: trunk

  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: trunk
      - deploy:
          requires:
            - build
